name: CI/CD

on: 
  push:
    branches: [test, devlop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Commit and Push changes
      uses: ad-m/github-push-action@v1
      with:
        repo: https://<PAT>@github.com/<username>/<repo>.git
        branch: test
        message: 'Automated commit and push'
    - name: Push to branch2
      uses: ad-m/github-push-action@v1
      with:
        repo: https://<PAT>@github.com/<username>/<repo>.git
        branch: devlop
        message: 'Push to branch2'    
        
