name: CI/CD

on: 
  push:
    branches: [test, devlop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Commit and Push changes
      uses: ad-m/github-push-action@master
      with:
        repo: https://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@github.com/sasender/thrones.git
        branch: test
        message: 'Automated commit and push'
    - name: Push to branch2
      uses: ad-m/github-push-action@master
      with:
        repo: https://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@github.com/sasender/thrones.git
        branch: devlop
        message: 'Push to branch2'    
        
